language: ruby
rvm:
  - 2.0.0

bundler_args: --without development

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database tacomanager_test;' -U postgres
  - bundle install
  - RAILS_ENV=test bundle exec rake db:create db:migrate
