development:
  adapter: postgresql
  encoding: unicode
  database: tacomanager_development
  pool: 5
  host: localhost
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: tacomanager_test
  pool: 5
  host: localhost
  username: postgres
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: tacomanager_production
  pool: 5
  host: localhost
  username: postgres
  password: 123
